routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookCategoryController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookIssueController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login', function(){
    return "Login";
})->name('login');
Route::get('/librarian/login',[AuthController::class,'showLibrarianLoginForm']);
Route::post('/librarian/login',[AuthController::class,'librarianLogin'])->name('librarian.login');

Route::middleware(['auth:librarian'])->prefix('librarian')->name('librarian.')->group( function (){
    Route::resource('/category', BookCategoryController::class);
    Route::resource('/author', AuthorController::class);
    Route::resource('/publisher', PublisherController::class);
    Route::resource('/book/issue', BookIssueController::class,[
        'as' => 'book'
    ]);
    Route::resource('/book', BookController::class);
    Route::resource('/user', UserController::class);

});

Route::get('/logout',[AuthController::class,'logout'])->name('logout');

//

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Book extends Model
{
    use HasFactory;
    protected $fillable = [
        'name', 'category_id', 'author_id', 'publisher_id' , 'short_description' ,'added_by'
    ];

    public function category()
    {
        return $this->belongsTo(BookCategory::class);
    }

    public function author()
    {
        return $this->belongsTo(Author::class);
    }

    public function publisher()
    {
        return $this->belongsTo(Publisher::class);
    }



}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use App\Models\Book;
use App\Models\BookCategory;
use App\Models\Publisher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with(['author:id,name','publisher:id,name'])->paginate(1,['id','name','author_id','publisher_id']);
        return view('book.manage',compact(['books']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = BookCategory::all(['id','name']);
        $authors = Author::all(['id','name']);
        $publishers = Publisher::all(['id','name']);
        return view('book.create',compact(['categories','authors','publishers']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'name' => ['required', 'string' , 'min:3'],
            'category_id' => ['required','numeric'],
            'author_id' => ['required','numeric'],
            'publisher_id' => ['required','numeric'],
            'short_description' => ['nullable', 'string' , 'min:30'],
        ]);
        $validate["added_by"] = Auth::user()->email;
        Book::create($validate);
        return response()->json(["status" => true, "msg" => "Book added successfully...!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id);
        return $book;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = BookCategory::all(['id','name']);
        $authors = Author::all(['id','name']);
        $publishers = Publisher::all(['id','name']);
        $book = Book::find($id);
        return view('book.edit',compact(['book','categories','authors','publishers']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $this->validate($request,[
            'name' => ['required', 'string' , 'min:3'],
            'category_id' => ['required','numeric'],
            'author_id' => ['required','numeric'],
            'publisher_id' => ['required','numeric'],
            'short_description' => ['nullable', 'string' , 'min:30'],
        ]);
        $validate["added_by"] = Auth::user()->email;
        Book::where('id',$id)->update($validate);
        return response()->json(["status" => true, "msg" => "Book updated successfully...!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();
        return response()->json(["status" => true, "msg" => "Book data deleted"]);
    }
}

resources/views/book/create.blade.php
@extends('layouts.master')
@section('title','Create Book | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Book /</span> Create Book</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>

          </div>
          <div class="card-body">
            <form id="bookForm" name="bookForm" >
              @csrf
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="title" name="name" placeholder="Enter a name" />
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Category</label>
                <select class="form-control" id="category_id" name="category_id">
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-category" class="invalid-feedback">
                    Select any category.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Author</label>
                <select class="form-control" id="author" name="author_id">
                    @foreach ($authors as $author)
                        <option value="{{$author->id}}">{{$author->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-author" class="invalid-feedback">
                    Select any author.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Publisher</label>
                <select class="form-control" id="publisher_id" name="publisher_id">
                    @foreach ($publishers as $publisher)
                        <option value="{{$publisher->id}}">{{$publisher->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-publisher" class="invalid-feedback">
                    Select any publisher.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-company">Short Discription</label>
                <input type="text" class="form-control" id="short-description" name="short_description" placeholder="Enter Short Discription (Max: 120 Character)" />
                <div id="invalid-short-description" class="invalid-feedback">
                    Enter Short Discription
                </div>
              </div>


              <button type="submit" class="btn btn-primary">Create Book</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });
  $("#category_id").on('change', function(e){
      $("#invalid-category").hide();
  });
  $("#author_id").on('change', function(e){
      $("#invalid-author").hide();
  });
  $("#publisher_id").on('change', function(e){
      $("#invalid-publisher").hide();
  });
  $("#short-description").on('input', function(e){
      $("#invalid-short-description").hide();
  });


  $("#bookForm").submit(function (e) {
      e.preventDefault();

      var formData = new FormData(this);

      $.ajax({
          url: "{{route('librarian.book.store')}}",
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
                  $(this)[0].reset();
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").show();
              }
              if (response.responseJSON.errors.category_id){
                  $("#invalid-category").show();
              }
              if (response.responseJSON.errors.author_id){
                  $("#invalid-author").show();
              }
              if (response.responseJSON.errors.publisher_id){
                  $("#invalid-publisher").show();
              }
              if (response.responseJSON.errors.short_description){
                  $("#invalid-short-description").show();
              }

          },
      });
  });
</script>
@endsection

resources/views/book/edit.blade.php
@extends('layouts.master')
@section('title','Edit Book | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Book /</span> Create Book</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>

          </div>
          <div class="card-body">
            <form id="bookForm" name="bookForm">
              @method('PATCH')
              @csrf
              <input type="hidden" name="book_id" id="book-id" value="{{$book->id}}">
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="title" name="name" placeholder="Enter a name" value="{{$book->name}}"/>
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Category</label>
                <select class="form-control" id="category_id" name="category_id">
                    @foreach ($categories as $category)
                        @if ($category->id == $book->category_id)
                            <option value="{{$category->id}}" selected>{{$category->name}}</option>
                        @endif
                            <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-category" class="invalid-feedback">
                    Select any category.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Author</label>
                <select class="form-control" id="author" name="author_id">
                    @foreach ($authors as $author)
                        @if ($author->id == $book->author_id)
                            <option value="{{$author->id}}" selected>{{$author->name}}</option>
                        @endif
                            <option value="{{$author->id}}">{{$author->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-author" class="invalid-feedback">
                    Select any author.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Publisher</label>
                <select class="form-control" id="publisher_id" name="publisher_id">
                    @foreach ($publishers as $publisher)
                        @if ($publisher->id == $book->publisher_id)
                            <option value="{{$publisher->id}}" selected>{{$publisher->name}}</option>
                        @endif
                        <option value="{{$publisher->id}}">{{$publisher->name}}</option>
                    @endforeach
                </select>
                <div id="invalid-publisher" class="invalid-feedback">
                    Select any publisher.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-company">Short Discription</label>
                <input type="text" class="form-control" id="short-description" name="short_description" placeholder="Enter Short Discription (Max: 300 Character)"  value="{{$book->short_description}}"/>
                <div id="invalid-short-description" class="invalid-feedback">
                    Enter Short Discription
                </div>
              </div>

              <button type="submit" class="btn btn-primary">Update Book</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });
  $("#category_id").on('change', function(e){
      $("#invalid-category").hide();
  });
  $("#author_id").on('change', function(e){
      $("#invalid-author").hide();
  });
  $("#publisher_id").on('change', function(e){
      $("#invalid-publisher").hide();
  });
  $("#short-description").on('input', function(e){
      $("#invalid-short-description").hide();
  });


  $("#bookForm").submit(function (e) {
      e.preventDefault();
      var formData = new FormData(this);
      var id = $("#book-id").val();
      $.ajax({
          url: "/librarian/book/"+id,
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").show();
              }
              if (response.responseJSON.errors.category_id){
                  $("#invalid-category").show();
              }
              if (response.responseJSON.errors.author_id){
                  $("#invalid-author").show();
              }
              if (response.responseJSON.errors.publisher_id){
                  $("#invalid-publisher").show();
              }
              if (response.responseJSON.errors.short_description){
                  $("#invalid-short-description").show();
              }

          },
      });
  });
</script>
@endsection

resources/views/book/manage.blade.php
@extends('layouts.master')
@section('title','Manage Books | iLibrary')
@section('venderCSS')
    <link rel="stylesheet" href="{{ asset( 'assets/vendor/css/pages/jquery.dataTables.min.css')}}" />
@endsection
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Book /</span> Manage Book</h4>
    @php
        $i = 1;
    @endphp
    <!-- Table -->
    <div class="card">
        <h5 class="card-header">Books</h5>
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>No.</th>
                <th>Book ID</th>
                <th>Book Name</th>
                <th>Author</th>
                <th>Publisher</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">

               @forelse ($books as $book)
                <tr>
                    <td>{{$i++}}</td>
                    <td>{{$book->id}}</td>
                    <td>{{$book->name}}</td>
                    <td>{{$book->author->name}}</td>
                    <td>{{$book->publisher->name}}</td>
                    <td>
                        <button type="button" class="btn btn-outline-primary" onclick="editBook({{$book->id}})">Edit</button>
                        <a href="javascript:void(0)" id="delete-book" data-id="{{ $book->id }}" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
               @empty
                <tr>No books...!</tr>
               @endforelse

            </tbody>
          </table>
        </div>
    </div>
    <!--/Table -->
    <div class="row">
        <div class="col">

          <div class="demo-inline-spacing">
            <!-- Basic Pagination -->
            <nav aria-label="Page navigation">

              {{$books->links('pagination::bootstrap-4')}}
            </nav>
            <!--/ Basic Pagination -->
          </div>
        </div>
      </div>
  </div>

@endsection

@section('js')
<script>

    function editBook(id) {
        location.href = "/librarian/book/"+id+"/edit";
    }
    $('body').on('click', '#delete-book', function () {
      var id = $(this).data("id");
      confirm("Are you sure want to delete !");
      $.ajax({
          url: "/librarian/book/"+id,
          data: {"_token": "{{ csrf_token() }}",},
          type: "DELETE",
          success: (response)=>{
              if(response.status == true){
                  $("#row-"+id).hide();
                  $("#msg").html(response.msg);
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
          },
        });
    });

  </script>
@endsection