routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookCategoryController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookIssueController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login', function(){
    return "Login";
})->name('login');
Route::get('/librarian/login',[AuthController::class,'showLibrarianLoginForm']);
Route::post('/librarian/login',[AuthController::class,'librarianLogin'])->name('librarian.login');

Route::middleware(['auth:librarian'])->prefix('librarian')->name('librarian.')->group( function (){
    Route::resource('/category', BookCategoryController::class);
    Route::resource('/author', AuthorController::class);
    Route::resource('/publisher', PublisherController::class);
    Route::resource('/book/issue', BookIssueController::class,[
        'as' => 'book'
    ]);
    Route::resource('/book', BookController::class);
    Route::resource('/user', UserController::class);

});

Route::get('/logout',[AuthController::class,'logout'])->name('logout');

//

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'institute_id',
        'is_employee',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected function password(): Attribute
    {
        return Attribute::make(
            set: fn ($value) => Hash::make($value),
        );
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate(1,['id','name','email','institute_id']);;
        return view('user.manage',compact(['users']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'name' => ['required','string','min:5'],
            'email'=> ['required','email','unique:users,email'],
            'institute_id' => ['required','string','min:5','unique:users,institude_id'],
            'password' => ['required','string'],
            'is_employee' => ['nullable'],
        ]);
        User::create($validate);
        return response()->json(["status" => true, "msg" => "User added successfully...!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('user.edit',compact(['user']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $this->validate($request,[
            'name' => ['required','string','min:5'],
            'email'=> ['required','email','unique:user,email,'.$id],
            'institute_id' => ['required','string','min:5','unique:users,institude_id,'.$id],
            'password' => ['nullable','string'],
            'is_employee' => ['nullable'],
        ]);
        if ($request->password) {
            User::where("id",$id)->update($validate);
        }else{
            User::where("id",$id)->update([
                'name' => $request->name,
                'email'=> $request->email,
                'institute_id' => $request->institude_id,
                'is_employee' => $request->is_employee,
            ]);
        }
        return response()->json(["status" => true, "msg" => "User data updated successfully...!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return response()->json(["status" => true, "msg" => "User data deleted...!"]);
    }
}

resources/views/user/create.blade.php
@extends('layouts.master')
@section('title','Create User | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">User /</span> Create User</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>

          </div>
          <div class="card-body">
            <form id="userForm" name="userForm" >
              @csrf
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="title" name="name" placeholder="Enter a name" />
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Email</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Enter a email" />
                <div id="invalid-email" class="invalid-feedback">
                    Please enter an email.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-institute_id">Enroll No. / Emp Code</label>
                <input type="text" class="form-control" id="institute_id" name="institute_id" placeholder="Enter a enroll / emp code" />
                <div id="invalid-institute-id" class="invalid-feedback">
                    Please enter an enroll no / emp code.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Password</label>
                <input type="text" class="form-control" id="password" name="password" placeholder="Enter a enroll / emp code" />
                <div id="invalid-password" class="invalid-feedback">
                    Please enter a password.
                </div>

              </div>

              <div class="mb-3">

                <input class="form-check-input" type="checkbox" value="1" name="is_employee" id="is_employee"  />
                <label class="form-check-label" for="is_employee">
                    is Emmployee ?
                </label>
                <div id="invalid-short-description" class="invalid-feedback">
                    Enter Short Discription
                </div>
              </div>


              <button type="submit" class="btn btn-primary">Create User</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });
  $("#email").on('input', function(e){
      $("#invalid-email").hide();
  });
  $("#institute_id").on('input', function(e){
      $("#invalid-institute-id").hide();
  });
  $("#password").on('input', function(e){
      $("#invalid-password").hide();
  });



  $("#userForm").submit(function (e) {
      e.preventDefault();

      var formData = new FormData(this);

      $.ajax({
          url: "{{route('librarian.user.store')}}",
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
                  $(this)[0].reset();
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").show();
              }
              if (response.responseJSON.errors.email){
                  $("#invalid-email").show();
              }
              if (response.responseJSON.errors.institute_id){
                  $("#invalid-institute-id").show();
              }
              if (response.responseJSON.errors.password){
                  $("#invalid-password").show();
              }
          },
      });
  });
</script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.master')
@section('title','Create User | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">User /</span> Edit User</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>

          </div>
          <div class="card-body">
            <form id="userForm" name="userForm" >
              @method('PATCH')
              @csrf
              <input type="hidden" name="user_id" id="user-id" value="{{$user->id}}">
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="title" name="name" placeholder="Enter a name" value="{{$user->name}}"/>
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Email</label>
                <input type="text" class="form-control" id="email" name="email" placeholder="Enter a email" value="{{$user->email}}"/>
                <div id="invalid-email" class="invalid-feedback">
                    Please enter an email.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-institute_id">Enroll No. / Emp Code</label>
                <input type="text" class="form-control" id="institute_id" name="institute_id" placeholder="Enter a enroll / emp code" value="{{$user->institute_id}}"/>
                <div id="invalid-institute-id" class="invalid-feedback">
                    Please enter an enroll no / emp code.
                </div>
              </div>

              <div class="mb-3">
                <label class="form-label" for="basic-default-phone">Password</label>
                <input type="text" class="form-control" id="password" name="password" placeholder="Enter a enroll / emp code" />
                <div id="invalid-password" class="invalid-feedback">
                    Please enter a password.
                </div>

              </div>

              <div class="mb-3">

                <input class="form-check-input" type="checkbox" value="1" name="is_employee" id="is_employee" @if ($user->is_employee)
                    @checked(true)
                @endif />
                <label class="form-check-label" for="is_employee">
                    is Emmployee ?
                </label>
                <div id="invalid-short-description" class="invalid-feedback">
                    Enter Short Discription
                </div>
              </div>


              <button type="submit" class="btn btn-primary">Update User</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });
  $("#email").on('input', function(e){
      $("#invalid-email").hide();
  });
  $("#institute_id").on('input', function(e){
      $("#invalid-institute-id").hide();
  });
  $("#password").on('input', function(e){
      $("#invalid-password").hide();
  });



  $("#userForm").submit(function (e) {
      e.preventDefault();
      var id = $("#user-id").val();
      var formData = new FormData(this);
      $.ajax({
          url: "/librarian/user/"+id,
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").show();
              }
              if (response.responseJSON.errors.email){
                  $("#invalid-email").show();
              }
              if (response.responseJSON.errors.institute_id){
                  $("#invalid-institute-id").show();
              }
              if (response.responseJSON.errors.password){
                  $("#invalid-password").show();
              }
          },
      });
  });
</script>
@endsection

resources/views/user/manage.blade.php
@extends('layouts.master')
@section('title','Manage Users | iLibrary')
@section('venderCSS')
    <link rel="stylesheet" href="{{ asset( 'assets/vendor/css/pages/jquery.dataTables.min.css')}}" />
@endsection
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">User /</span> Manage User</h4>
    @php
        $i = 1;
    @endphp
    <!-- Table -->

    <div class="card">
        <h5 class="card-header">Users</h5>
        <p id="msg"></p>
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>No.</th>
                <th>User Name</th>
                <th>Email</th>
                <th>Institude ID</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">

               @forelse ($users as $user)
                <tr id="row-{{$user->id}}">
                    <td>{{$i++}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->institute_id}}</td>
                    <td>
                        <button type="button" class="btn btn-outline-primary" onclick="editUser({{$user->id}})">Edit</button>
                        <a href="javascript:void(0)" id="delete-user" data-id="{{ $user->id }}" class="btn btn-outline-danger">Delete</a>

                    </td>
                </tr>
               @empty
                <tr>No books...!</tr>
               @endforelse

            </tbody>
          </table>
        </div>
    </div>
    <!--/Table -->
    <div class="row">
        <div class="col">

          <div class="demo-inline-spacing">
            <!-- Basic Pagination -->
            <nav aria-label="Page navigation">

              {{$users->links('pagination::bootstrap-4')}}
            </nav>
            <!--/ Basic Pagination -->
          </div>
        </div>
      </div>
  </div>



@endsection

@section('js')
  <script>

    function editUser(id) {
        location.href = "/librarian/user/"+id+"/edit";
    }

    $('body').on('click', '#delete-user', function () {
      var id = $(this).data("id");
      confirm("Are you sure want to delete !");
      $.ajax({
          url: "/librarian/user/"+id,
          data: {"_token": "{{ csrf_token() }}",},
          type: "DELETE",
          success: (response)=>{
              if(response.status == true){
                  $("#row-"+id).hide();
                  $("#msg").html(response.msg);
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
          },
        });
    });



  </script>
@endsection