routes/web.php
<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookCategoryController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\BookIssueController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login', function(){
    return "Login";
})->name('login');
Route::get('/librarian/login',[AuthController::class,'showLibrarianLoginForm']);
Route::post('/librarian/login',[AuthController::class,'librarianLogin'])->name('librarian.login');

Route::middleware(['auth:librarian'])->prefix('librarian')->name('librarian.')->group( function (){
    Route::resource('/category', BookCategoryController::class);
    Route::resource('/author', AuthorController::class);
    Route::resource('/publisher', PublisherController::class);
    Route::resource('/book/issue', BookIssueController::class,[
        'as' => 'book'
    ]);
    Route::resource('/book', BookController::class);
    Route::resource('/user', UserController::class);

});

Route::get('/logout',[AuthController::class,'logout'])->name('logout');

//

app/Models/Author.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Author;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = Author::paginate(10,['id','name']);
        return view('author.manage',compact(["authors"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => ['required','string','min:3','unique:authors,name'],
        ]);

        Author::create(['name' => $request->name,]);

        return response()->json(["status" => true, "msg" => "Author added successfully...!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function show(Author $author)
    {
        return $author;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit(Author $author)
    {
        return view('author.edit', compact(['author']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => ['required','string','min:3','unique:authors,name,'.$id],
        ]);
        Author::where('id',$id)->update(["name"=>$request->name]);
        return response()->json(["status" => true, "msg" => "Author update successfully...!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {
        $author->delete();
        return response()->json(["status" => true, "msg" => "Author data deleted...!"]);
    }
}

resources/views/author/create.blade.php
@extends('layouts.master')
@section('title','Create Author | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Author /</span> Create Auhor</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>
          </div>
          <div class="card-body">
            <form id="authorForm" name="authorForm">
              @csrf
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter a name" />
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Create Author</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });

  $("#authorForm").submit(function (e) {
      e.preventDefault();
      var formData = new FormData(this);

      $.ajax({
          url: "{{route('librarian.author.store')}}",
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
                  $(this)[0].reset();
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").html(response.responseJSON.errors.name);
                  $("#invalid-name").show();
              }

          },
      });
  });
</script>
@endsection

resources/views/author/edit.blade.php
@extends('layouts.master')
@section('title','Create Author | iLibrary')
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Author /</span> Edit Auhor</h4>

    <!-- Basic Layout -->
    <div class="row">
      <div class="col-xl">
        <div class="card mb-4">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h5 id="msg" class="mb-0">Fill Details</h5>
          </div>
          <div class="card-body">
            <form id="authorForm" name="authorForm">
              @method('PATCH')
              @csrf
              <input type="hidden" name="author_id" id="author-id" value="{{$author->id}}">
              <div class="mb-3">
                <label class="form-label" for="basic-default-fullname">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter a name" value="{{$author->name}}"/>
                <div id="invalid-name" class="invalid-feedback">
                    Please enter a name.
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Update Author</button>
            </form>
          </div>
        </div>
      </div>

    </div>
  </div>
@endsection
@section('js')
<script>
  $("#name").on('input', function(e){
      $("#invalid-name").hide();
  });

  $("#authorForm").submit(function (e) {
      e.preventDefault();
      var id = $("#author-id").val();
      var formData = new FormData(this);

      $.ajax({
          url: "/librarian/author/"+id,
          data: formData,
          type: "POST",
          cache: false,
          contentType: false,
          processData: false,
          success: (response)=>{
              if(response.status == true){
                  $("#msg").html(response.msg);
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
              if (response.responseJSON.errors.name) {
                  $("#invalid-name").html(response.responseJSON.errors.name);
                  $("#invalid-name").show();
              }

          },
      });
  });
</script>
@endsection

resources/views/author/manage.blade.php
@extends('layouts.master')
@section('title','Manage Authors | iLibrary')
@section('venderCSS')
    <link rel="stylesheet" href="{{ asset( 'assets/vendor/css/pages/jquery.dataTables.min.css')}}" />
@endsection
@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Author /</span> Manage Author</h4>
    @php
        $i = 1;
    @endphp
    <!-- Table -->

    <div class="card">
        <h5 class="card-header">Authors</h5>
        <p id="msg"></p>
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead>
              <tr>
                <th>No.</th>
                <th>Author Name</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">

               @forelse ($authors as $author)
                <tr id="row-{{$author->id}}">
                    <td>{{$i++}}</td>
                    <td>{{$author->name}}</td>
                    <td>
                        <button type="button" class="btn btn-outline-primary" onclick="editAuthor({{$author->id}})">Edit</button>
                        <a href="javascript:void(0)" id="delete-author" data-id="{{ $author->id }}" class="btn btn-outline-danger">Delete</a>

                    </td>
                </tr>
               @empty
                <tr>No Authors...!</tr>
               @endforelse

            </tbody>
          </table>
        </div>
    </div>
    <!--/Table -->
    <div class="row">
        <div class="col">

          <div class="demo-inline-spacing">
            <!-- Basic Pagination -->
            <nav aria-label="Page navigation">

              {{$authors->links('pagination::bootstrap-4')}}
            </nav>
            <!--/ Basic Pagination -->
          </div>
        </div>
      </div>
  </div>



@endsection

@section('js')
  <script>

    function editAuthor(id) {
        location.href = "/librarian/author/"+id+"/edit";
    }

    $('body').on('click', '#delete-author', function () {
      var id = $(this).data("id");
      confirm("Are you sure want to delete !");
      $.ajax({
          url: "/librarian/author/"+id,
          data: {"_token": "{{ csrf_token() }}",},
          type: "DELETE",

          success: (response)=>{
              if(response.status == true){
                  $("#row-"+id).hide();
                  $("#msg").html(response.msg);
                  $(this)[0].reset();
              }
              else{
                  $("#msg").html(response.msg);
              }
          },
          error: (response)=>{
              console.log(response);
          },
        });
    });




  </script>
@endsection